version: '3'
services:
  react-app:
    build:
      context: . #where should files and folders be pulled from
      dockerfile: Dockerfile.dev
    ports: 
      - "3000:3000"
    volumes:
      - /app/node_modules 
      - .:/app
  tests:
    build:
      context: . #where should files and folders be pulled from
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules 
      - .:/app
    command: ["npm", "run", "test"]
